# Generated by Django 3.1.5 on 2021-02-01 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GonderiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazi', models.TextField()),
                ('kayitzaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('yayimzaman', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
