# Generated by Django 3.1.5 on 2021-02-01 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gonderimodel',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='kayitzaman',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kayıt Tarih Saat'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='yayimzaman',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayın Zaman Tarih Saat'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='yazi',
            field=models.TextField(verbose_name='Yazı'),
        ),
    ]
