# Generated by Django 3.1.5 on 2021-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210201_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderimodel',
            name='tur',
            field=models.CharField(choices=[('1', 'Korku'), ('2', 'Komedi'), ('3', 'Günlük')], default='1', max_length=8),
        ),
    ]
